{% set version = "0.5.2" %}

package:
  name: sudospawner
  version: {{ version }}

source:
  fn: sudospawner-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/sudospawner/sudospawner-{{ version }}.tar.gz
  sha256: 5dbddd8164e05e4bb3a31eeb1a5baf5a5c6268f1cd14b3f063cde609b8bfbbe1

build:
  number: 1000
  skip: true  # [win or py2k]
  script: pip install --no-deps .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - jupyterhub >=0.4

test:
  imports:
    - sudospawner

about:
  home: https://github.com/jupyterhub/sudospawner
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Enables JupyterHub to spawn single-user notebook servers without being root

extra:
  recipe-maintainers:
    - minrk
    - parente
