{% set version = "0.5.1" %}

package:
  name: sudospawner
  version: {{ version }}

source:
  fn: sudospawner-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/sudospawner/sudospawner-{{ version }}.tar.gz
  sha256: a0e483ad1bbf1fa7829ba567cb72d4171c207c577f8e9aef7b36484066a3b430

build:
  number: 0
  skip: true  # [win or py2k]
  script: pip install --no-deps .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - jupyterhub >=0.4

test:
  imports:
    - sudospawner

about:
  home: https://github.com/jupyterhub/sudospawner
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Enables JupyterHub to spawn single-user notebook servers without being root

extra:
  recipe-maintainers:
    - minrk
    - parente
