travis:
  secure:
    BINSTAR_TOKEN: AeUWNt3F3GQGjqlb/EYsYgZ3h6byciyFi9IPF6aLu9x+d8bf/L/Y1VdZP8UwUFt2Q44JHvlvgQ/kOpReP0GYdhB4WFFXGMD/kGWg1JtKv06PwH2HRgftJLytPx157vga7PHk3hHFIpBeqcTdD5wft10JBQpYSuZOHEzYUzrxFx0vKVvUOQ9CKw2ljFcEzLCFKIH8t/zC5wEPELQpxCMHHHWQQxB3R1p+nCwlXhXMBWwyITH6GMEANh6CH7rlIYbt86Fl32n5r4bvEOC+NUWCrKC8u7sHpMEfRYcNqCQguMSmoFj0ZtSAE2EePiee2fvsL+xFnE6AWa+VvW+Cuq7+0WuPkfP/DRvdbH9tf/wpYIV33MXh6FNzMahSftGAsbvDXWh3r3Fvd/Eaf7gxQEFrdsQojafmfcikKYyKFhHbcRjGZWptJty6plRmYnlar0bI0MA3jsCu4ikoUDdmD73k/yAhaGP/iBUM9c5H/zkqMqoRojMnAcUnb2Y2S9C7VnMeT5O8WDObv4nGTD34PNdF5q/QwZVhZBHQP5szWWUbh7LRlnG7V0yI9wdidWeN31iNoaxFg+O7q15agjNSyY8QSppSKh1YeruuM0gnaWIB7GNOXjh7FwiD6E14zItkdxXMIHQ1TQGzhtJyg4HS/OEaf0xWJHcdutyv0jkpfimOcqw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
