appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ugxSpEKpRzi1tCzM43tqK2/UqHGZdogjDfelT/xBfK/dTYXivBFmuVvPaLkoJlrTESUmImlAzvTRnFu/yf1FbCJ6LXXxB48bq2dAAf1/UcBf8McXkBva/OJx7e6vCz11R4yGn1DPzEq57UaBsqBiMoDjzBKLi0Nt/odD2fOyZVmorFIUb0QwdFfOJbrgx29oRV9MqAePlVW5cw+VY2L4h7F/ShFp7ewFZX/YAaqaQ6NiBy2r3ZDZ4qEFaUo3EJIGrLkTbveX7go6HXaWvdkTgYkSZxiViT57F91zq8XExNXhaWIq2ALMi0IB1GeoikER3TaXsVZ7r08YqI5Qz7kdP/X7+MELAknX5cXm2TA48qxzdP/JVEqOV7SsfQCvQqLv8hZcvvXHHiIVP/hhKDO878RnvPBDwIHDf6FfKAqYOipG+0ZD/r9nrTRzWaog57BEgo+FsccgTu9XBNqzK3cBgwFGQqj2pfK1pcJ/j9zy4r6IGwqTJ5VcX1cE8AVITxVPeKUHB8zaIauPUwFEJZQkhsc1IarGJwuhogedvO/GBpbOX+U0AQJfzjFllCxA0AT11hqohWb6Stv2z/svNUxP6yu0ZCKmMkC1AeKS/JDt2xZNBn/LAOE2uvkbXs7PAE01t7HxWWIK1UUpAx6rPqhmxb/9dXZ4reR5qcm0M1OAyKM=}
conda_forge_output_validation: true
